migrate docs to typescript
skbkontur/react-ui-validations pull request #41
Opened 2019-02-11 05:18 UTC by slawwan

2019-02-15 09:51 UTC, wKich commented on tsconfig.json
> +                "typings/*"
Злой чит

2019-02-15 10:47 UTC, wKich requested changes

2019-02-15 10:47 UTC, wKich commented on package.json
> -        "lint": "eslint docs --ext .js,.jsx",
Если выпиливаешь eslint, давай везде выпилим. Из зависимостей например тоже

2019-02-15 10:47 UTC, wKich commented on package.json
> -        "lint": "eslint docs --ext .js,.jsx",
И похоже что эта правка к другому коммиту относится

2019-02-15 10:47 UTC, wKich commented on docs/components/Pages/Concepts/QuickValidations/QuickValidations.tsx
> +import Link from "retail-ui/components/Link/Link";
А чем предыдущий импорт не устроил?

2019-02-15 10:47 UTC, wKich commented on package.json
> +    "typings": "./typings",
Это шляпа не будет работать. Тут надо указывать путь до главного файла с тайпингами

2019-02-15 10:55 UTC, slawwan commented on tsconfig.json
> +                "typings/*"
это чтобы подложить тайпинги для компонентов retail-ui, так как версия либы контролов старенькая, не для всего есть

2019-02-15 10:59 UTC, slawwan commented on docs/components/Pages/Concepts/QuickValidations/QuickValidations.tsx
> +import Link from "retail-ui/components/Link/Link";
в `"retail-ui/components/Button"` нет default-экспорта, то есть надо либо мой вариант либо `import {Button} from "retail-ui/components/Button"`;

2019-02-15 10:59 UTC, slawwan commented on package.json
> +    "typings": "./typings",
это я херню походу какую-то запушал

2019-02-15 11:09 UTC, slawwan commented on package.json
> -        "lint": "eslint docs --ext .js,.jsx",
выкосил все про eslint

2019-02-15 11:09 UTC, slawwan commented on package.json
> +    "typings": "./typings",
выкосил

2019-02-18 06:56 UTC, slawwan commented on docs/components/Pages/Concepts/QuickValidations/QuickValidations.tsx
> +import Link from "retail-ui/components/Link/Link";
прибрал

2019-02-18 08:51 UTC, wKich approved these changes

2019-02-18 18:07 UTC, merged